"""
Tresor Couture — Instagram kit specs.

50 deliverables, all in the Tresor voice: curated, restrained, museum-archival,
present tense, no emojis, no exclamation marks. Each spec is consumed by
render.py to emit either a 1080x1920 Reel-ready MP4 (no audio) or a
1080x1350 portrait JPG.

Field reference:
  id            stable filename suffix (e.g. "01-new-arrival")
  kind          "video" | "post"
  category      shown as the tiny uppercase eyebrow label
  hook          serif headline (8-10 words max)
  body          list[str] — short body lines (3-5 lines, 60ch each)
  cta           bottom call-to-action ("SHOP THE EDIT", "LINK IN BIO" etc.)
  accent        optional "rule" | "monogram" — decorative middle element
"""

from pathlib import Path

ROOT  = Path(__file__).resolve().parent
OUT_V = ROOT / "videos"
OUT_P = ROOT / "posts"

# ---------------------------------------------------------------------------
# 20 video specs (Reels, 1080x1920, 8s, no audio)
# ---------------------------------------------------------------------------

VIDEOS = [
    dict(
        id="01-new-arrival",
        category="THE ARCHIVE",
        hook="A new piece, quietly arrived.",
        body=["Handpicked from a maker we trust.",
              "Limited. Unrepeatable. Yours, or someone else's."],
        cta="SHOP THE EDIT",
    ),
    dict(
        id="02-the-dress",
        category="A SINGLE PIECE",
        hook="The dress that earns the question.",
        body=["The one strangers ask about.",
              "Cut to flatter. Priced to keep."],
        cta="DISCOVER THE PIECE",
    ),
    dict(
        id="03-capsule",
        category="THE CAPSULE",
        hook="Three pieces. Nine ways to wear them.",
        body=["The foundation. The statement. The wildcard.",
              "Built to dress a week without repeating."],
        cta="EXPLORE THE CAPSULE",
    ),
    dict(
        id="04-pov-aesthetic",
        category="THE EDIT",
        hook="Finally, a boutique that reads your taste.",
        body=["No endless scroll. No reluctant purchases.",
              "Pieces that read like you, only sharper."],
        cta="OPEN THE LOOKBOOK",
    ),
    dict(
        id="05-detail-shot",
        category="THE DETAILS",
        hook="It is in the detailing that quality declares itself.",
        body=["Hand-finished edges. Considered buttons.",
              "Fabric that holds its weight."],
        cta="STUDY THE PIECE",
    ),
    dict(
        id="06-restock",
        category="RETURNED",
        hook="Restocked by demand. Briefly.",
        body=["The piece that sold through in forty-eight hours.",
              "Back. In smaller numbers."],
        cta="CLAIM YOURS",
    ),
    dict(
        id="07-add-to-cart",
        category="THE TRANSITION",
        hook="One drop. Three silhouettes.",
        body=["A single arrival, styled three distinct ways.",
              "Pick the one that argues with your wardrobe."],
        cta="SHOP ALL THREE",
    ),
    dict(
        id="08-luxury-for-less",
        category="THE FORMULA",
        hook="The look that reads costlier than it is.",
        body=["A full outfit, considered piece by piece.",
              "Quietly luxurious. Honestly priced."],
        cta="BUILD THE LOOK",
    ),
    dict(
        id="09-desk-to-dinner",
        category="DAY TO NIGHT",
        hook="One piece. Morning meeting to late dinner.",
        body=["Pair it with a blazer for the desk.",
              "Lose the blazer. Add earrings. The night begins."],
        cta="SHOP THE PIECE",
    ),
    dict(
        id="10-unboxing",
        category="THE UNBOXING",
        hook="A package that opens like a small ceremony.",
        body=["Tissue. Hand-folded. A note.",
              "The way a piece should arrive."],
        cta="ORDER FROM THE EDIT",
    ),
    dict(
        id="22-expensive-formula",
        category="STYLING NOTE",
        hook="The formula for looking quietly expensive.",
        body=["Tuck the shirt. Add a structured layer.",
              "One considered accessory. Never five."],
        cta="READ THE FULL NOTE",
    ),
    dict(
        id="24-outfit-repeater",
        category="ON VERSATILITY",
        hook="The same dress, four different occasions.",
        body=["Wedding. Office. Brunch. Night.",
              "One piece, learning new languages."],
        cta="SEE EACH WAY",
    ),
    dict(
        id="26-layering",
        category="LAYERING NOTE",
        hook="Thin layers, never bulk.",
        body=["A fitted base. A light knit. A structured outer.",
              "Keep the bottom fitted when the top is layered."],
        cta="BROWSE THE LAYERS",
    ),
    dict(
        id="28-styling-fix",
        category="THE FIX",
        hook="The wrong way, and the considered way.",
        body=["One small adjustment changes the entire piece.",
              "Tailoring is cheaper than you think."],
        cta="LET US STYLE IT",
    ),
    dict(
        id="30-thirty-seconds",
        category="THE FORMULA",
        hook="Thirty seconds, and you are dressed.",
        body=["A flattering base. A single layer.",
              "Shoes for the occasion. One accessory. Done."],
        cta="SHOP THE BASES",
    ),
    dict(
        id="62-main-character",
        category="ON CONFIDENCE",
        hook="It is only coffee. Still, you wear the piece.",
        body=["The morning becomes cinematic.",
              "Confidence arrives before the espresso."],
        cta="DRESS FOR YOURSELF",
    ),
    dict(
        id="66-airport-fit",
        category="ON TRAVEL",
        hook="An airport outfit that reads composed.",
        body=["Coordinated. Considered. Comfortable.",
              "Sneakers acceptable. Sloppy never."],
        cta="SHOP THE TRAVEL EDIT",
    ),
    dict(
        id="68-date-night",
        category="ON PRESENCE",
        hook="The piece that makes them forget the sentence.",
        body=["Not about them.",
              "About the way the piece carries you."],
        cta="FIND YOUR PIECE",
    ),
    dict(
        id="92-outfit-check",
        category="OUTFIT CHECK",
        hook="Mirror. Street. Coffee. Office. Dinner.",
        body=["One outfit. Five places. No changes.",
              "The reward of a well-curated piece."],
        cta="SHOP THE PIECE",
    ),
    dict(
        id="99-confidence",
        category="ON BECOMING",
        hook="It is not the clothes. It is how they make you stand.",
        body=["You speak differently.",
              "You take up the room differently."],
        cta="FIND YOUR CONFIDENCE PIECE",
    ),
]

# ---------------------------------------------------------------------------
# 30 post specs (1080x1350 portrait JPG, Meta feed-safe)
# ---------------------------------------------------------------------------

POSTS = [
    dict(
        id="11-bts-curated",
        category="BEHIND THE WORK",
        hook="This is what a boutique looks like before the camera.",
        body=["Not a warehouse. Not mass-production.",
              "A room where each piece is chosen, checked, styled.",
              "Quality is a process, not a claim."],
        cta="VISIT THE STUDIO",
    ),
    dict(
        id="12-why-we-started",
        category="THE BEGINNING",
        hook="We started because the websites all looked the same.",
        body=["Tresor was built for the piece you do not see elsewhere.",
              "Quality that survives the third wash.",
              "Cuts that fit real bodies."],
        cta="READ OUR STORY",
    ),
    dict(
        id="14-meet-the-maker",
        category="MEET THE CURATOR",
        hook="The face behind the pieces you love.",
        body=["I source every piece personally.",
              "I write every thank-you note.",
              "This is a love letter to slow fashion, not a business plan."],
        cta="FOLLOW ALONG",
    ),
    dict(
        id="16-our-standards",
        category="THE STANDARDS",
        hook="Every piece in this archive passes four tests.",
        body=["Quality. Fit. Vibe. Value.",
              "If any one is missing, you will not see it here."],
        cta="LEARN MORE",
    ),
    dict(
        id="18-the-journey",
        category="THE JOURNEY",
        hook="From a borrowed bedroom to a quiet community.",
        body=["Year one: fifty orders, one spare room.",
              "Now: a community that built this dream with us.",
              "Every order, a thank-you we still mean."],
        cta="JOIN US",
    ),
    dict(
        id="20-no-sales",
        category="ON PRICING",
        hook="Why we do not run sales every weekend.",
        body=["Because the prices are already fair.",
              "Because the pieces are already worth it.",
              "When we do mark down, it is real, and it is rare."],
        cta="SUBSCRIBE FOR FIRST LOOKS",
    ),
    dict(
        id="21-five-ways-shirt",
        category="STYLING GUIDE",
        hook="One white shirt. Five different silhouettes.",
        body=["Tucked. Knotted. Layered. Oversized. Half-tucked.",
              "The shirt that quietly rebuilds a wardrobe."],
        cta="SHOP THE SHIRT",
    ),
    dict(
        id="23-three-accessories",
        category="THE RULE OF THREE",
        hook="Every considered outfit wears exactly three accessories.",
        body=["Something that shines.",
              "Something that structures.",
              "Something that ties it together. Never more."],
        cta="BROWSE ACCESSORIES",
    ),
    dict(
        id="25-color-combos",
        category="COLOUR STUDY",
        hook="Five pairings our stylists return to, season after season.",
        body=["Sage and cream. Navy and mustard.",
              "Blush and chocolate. Black and cobalt.",
              "Terracotta and ivory. Quiet, lasting choices."],
        cta="EXPLORE THE PALETTE",
    ),
    dict(
        id="27-universal-shoes",
        category="THE FIVE",
        hook="Five shoes that pair with most of this archive.",
        body=["White sneakers. Nude heels. Black ankle boots.",
              "Strappy sandals. A pair of loafers.",
              "The universals."],
        cta="SHOP FOOTWEAR",
    ),
    dict(
        id="29-dress-code",
        category="THE DECODER",
        hook="What smart casual actually means.",
        body=["Tailored pieces, relaxed elements.",
              "One statement, maximum.",
              "Quality fabrics. Polished footwear. No logos."],
        cta="READ THE GUIDE",
    ),
    dict(
        id="31-first-piece",
        category="FROM A CUSTOMER",
        hook="She ordered one piece. She kept ordering.",
        body=["“I bought a dress to test the quality.”",
              "“Now I have seven, and my wardrobe finally agrees with me.”",
              "— A reader in Bombay."],
        cta="START WITH ONE",
    ),
    dict(
        id="33-the-review",
        category="A NOTE WE KEEP",
        hook="The review that arrived on a quiet Tuesday.",
        body=["“For the first time, the clothes were made for me,",
              "not just in my size.”",
              "This is the reason for the work."],
        cta="READ MORE REVIEWS",
    ),
    dict(
        id="35-transformation",
        category="THE SHIFT",
        hook="Before: nothing to wear. After: too much to choose from.",
        body=["A wardrobe is not a closet.",
              "It is a set of options. We build the options."],
        cta="BUILD YOURS",
    ),
    dict(
        id="37-repeat-customers",
        category="THE LOOP",
        hook="The customer who returns is the highest review.",
        body=["First order: testing.",
              "Second: trusting.",
              "Fourth: family."],
        cta="JOIN THE FAMILY",
    ),
    dict(
        id="39-compliments",
        category="ONE EVENING",
        hook="The piece that earned forty-seven compliments.",
        body=["Worn to a wedding.",
              "Strangers asked. Friends asked.",
              "The same question, all evening."],
        cta="FIND YOUR PIECE",
    ),
    dict(
        id="41-seasonal-essentials",
        category="SEASONAL EDIT",
        hook="The five pieces that carry the season.",
        body=["A transitional layer. A statement knit.",
              "A versatile boot. An elevated basic.",
              "One occasion piece, for everything that arrives."],
        cta="SHOP THE EDIT",
    ),
    dict(
        id="43-event-outfit",
        category="THE OCCASION",
        hook="An event-outfit edit that is not basic.",
        body=["Modern traditional. Minimalist statement.",
              "Bold colour. Textured mix. Unexpected silhouette.",
              "Five ways to be remembered."],
        cta="DRESS THE EVENING",
    ),
    dict(
        id="45-color-story",
        category="COLOUR STORY",
        hook="The shades this season returns to.",
        body=["Soft. Earthy. Sunlit. Neutral. Bold.",
              "Five tones that hold across moods and months."],
        cta="EXPLORE BY COLOUR",
    ),
    dict(
        id="49-capsule-twelve",
        category="THE CAPSULE",
        hook="Twelve pieces. Thirty outfits. One coherent wardrobe.",
        body=["Tops, bottoms, layers, dresses, shoes.",
              "Curated to talk to each other.",
              "Designed to outlast the trend cycle."],
        cta="BUILD THE CAPSULE",
    ),
    dict(
        id="61-sunday-reset",
        category="A SUNDAY",
        hook="The Sunday reset, dressed.",
        body=["Sleep. Coffee. Audit the wardrobe.",
              "Choose intentionally. Plan the week.",
              "Confidence is a routine, not an accident."],
        cta="JOIN THE RITUAL",
    ),
    dict(
        id="65-weekend-planner",
        category="THE PLANNER",
        hook="Your weekend, dressed in advance.",
        body=["Friday evening. Saturday brunch.",
              "Saturday night. Sunday slow.",
              "Four outfits, considered, ready."],
        cta="PLAN WITH US",
    ),
    dict(
        id="67-that-girl",
        category="ON INTENTION",
        hook="It is not about being perfect. It is about being intentional.",
        body=["Pieces that fit. Quality you can feel.",
              "Colours that talk. Items that spark something.",
              "Dress for the life you want."],
        cta="START WITH ONE PIECE",
    ),
    dict(
        id="69-self-care-wardrobe",
        category="ON RITUAL",
        hook="Your clothes affect your mood. Your mood, your week.",
        body=["Declutter. Organise. Identify the gaps.",
              "Browse with intent. Plan five outfits.",
              "Five stress-free mornings."],
        cta="REFRESH WITH US",
    ),
    dict(
        id="81-fabric-guide",
        category="FABRIC 101",
        hook="Linen, silk, cotton, crepe — know what you are buying.",
        body=["Linen breathes and wrinkles.",
              "Silk drapes and asks for care.",
              "Cotton lives in any wardrobe. Crepe forgives."],
        cta="READ THE FULL GUIDE",
    ),
    dict(
        id="83-cheap-mistakes",
        category="ON FIT",
        hook="Five details that make any outfit read cheap.",
        body=["Wrong undergarments. Ill-fitting cut.",
              "Too many trends. Wrong shoes.",
              "Over-accessorising. The fix is small. Always."],
        cta="READ THE NOTE",
    ),
    dict(
        id="85-seventy-twenty-ten",
        category="THE ARCHITECTURE",
        hook="A wardrobe in three ratios: 70, 20, 10.",
        body=["Seventy per cent basics. The workhorses.",
              "Twenty per cent statements. The compliments.",
              "Ten per cent trends. The fun. The replaceable."],
        cta="BUILD YOURS",
    ),
    dict(
        id="87-care-labels",
        category="ON LONGEVITY",
        hook="The care label, read literally.",
        body=["Wash cold means cold.",
              "Dry flat means flat.",
              "These pieces are investments. Treat them that way."],
        cta="SAVE THE GUIDE",
    ),
    dict(
        id="89-color-theory",
        category="COLOUR THEORY",
        hook="Four ways colour builds an outfit.",
        body=["Monochrome elongates.",
              "Complementary commands.",
              "Analogous calms. Neutral plus pop, almost always works."],
        cta="STUDY THE PALETTE",
    ),
    dict(
        id="90-invest-vs-save",
        category="THE STRATEGY",
        hook="Where to invest. Where to save.",
        body=["Invest in outerwear, shoes, bags, tailoring.",
              "Save on trends and occasion pieces.",
              "A wardrobe is a budget, allocated."],
        cta="READ THE STRATEGY",
    ),
]

assert len(VIDEOS) == 20, f"want 20 videos, got {len(VIDEOS)}"
assert len(POSTS)  == 30, f"want 30 posts, got {len(POSTS)}"
